INSERT INTO RESTAURANT(RESTAURANT_NAME) VALUES('Restaurant 1');
INSERT INTO RESTAURANT(RESTAURANT_NAME) VALUES('Restaurant 2');

INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(6,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(6,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(6,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(6,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(4,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(4,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(4,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(4,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(2,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(2,1);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(12,1);

INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(6,2);
INSERT INTO RESTAURANT_TABLE(SEATING_CAPACITY,RESTAURANT_ID) VALUES(6,2);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
  values ('sa','$2a$10$K3LbQvLKdnAz/erqt3kZceo/7I6aPkdrG4qJsHFZiUARWBwI2mnra',1);
 
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
  values ('sa', 'ROLE_SYS_ADMIN');