DROP TABLE IF EXISTS RESTAURANT;
CREATE TABLE RESTAURANT(
  RESTAURANT_ID INT AUTO_INCREMENT  PRIMARY KEY
);
 
DROP TABLE IF EXISTS RESTAURANT_TABLE;
CREATE TABLE RESTAURANT_TABLE(
  TABLE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  RESTAURANT_ID INT NOT NULL,
  foreign key (RESTAURANT_ID) references RESTAURANT(RESTAURANT_ID)
);

DROP TABLE IF EXISTS TABLE_RESERVATION;
CREATE TABLE RESERVATION(
  RESERVATION_ID INT AUTO_INCREMENT  PRIMARY KEY,
  TABLE_ID INT NOT NULL,
  RESTAURANT_ID INT NOT NULL,
  foreign key (RESTAURANT_ID) references RESTAURANT(RESTAURANT_ID),
  foreign key (TABLE_ID) references RESTAURANT_TABLE(TABLE_ID)
);