DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS RESTAURANT_TABLE;
DROP TABLE IF EXISTS RESTAURANT;

create table USERS(
USERNAME varchar_ignorecase(50) not null primary key,
PASSWORD varchar_ignorecase(500) not null,
enabled boolean not null);

CREATE TABLE AUTHORITIES (
  USERNAME VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
 
CREATE UNIQUE INDEX ix_auth_username
  on authorities (username,authority);
  
CREATE TABLE RESTAURANT(
  RESTAURANT_ID INT AUTO_INCREMENT  PRIMARY KEY,
  RESTAURANT_NAME VARCHAR(32) NOT NULL
);
 
ALTER TABLE RESTAURANT ADD CONSTRAINT UNIQUE_NAME UNIQUE(RESTAURANT_NAME);

CREATE TABLE RESTAURANT_TABLE(
  TABLE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  SEATING_CAPACITY INT NOT NULL,
  RESTAURANT_ID INT NOT NULL,
  foreign key (RESTAURANT_ID) references RESTAURANT(RESTAURANT_ID)
);

CREATE TABLE RESERVATION(
  RESERVATION_ID INT AUTO_INCREMENT  PRIMARY KEY,
  TABLE_ID INT NOT NULL,
  START TIMESTAMP NOT NULL,
  END TIMESTAMP NOT NULL,
  foreign key (TABLE_ID) references RESTAURANT_TABLE(TABLE_ID)
);

