DELETE FROM AUTHORITIES;
DELETE FROM USERS;
DELETE FROM RESERVATION;
DELETE FROM RESTAURANT_TABLE;
DELETE FROM RESTAURANT;

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
  values ('sa','$2a$10$K3LbQvLKdnAz/erqt3kZceo/7I6aPkdrG4qJsHFZiUARWBwI2mnra',1);
 
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
  values ('sa', 'ROLE_SYS_ADMIN');