CREATE SCHEMA IF NOT EXISTS TEST;
DROP TABLE IF EXISTS TEST.RESERVATION;
DROP TABLE IF EXISTS TEST.RESTAURANT_TABLE;
DROP TABLE IF EXISTS TEST.RESTAURANT;

CREATE TABLE TEST.RESTAURANT(
  RESTAURANT_ID INT AUTO_INCREMENT  PRIMARY KEY,
  RESTAURANT_NAME VARCHAR(32) NOT NULL
);
 
ALTER TABLE TEST.RESTAURANT ADD CONSTRAINT UNIQUE_NAME UNIQUE(RESTAURANT_NAME);

CREATE TABLE TEST.RESTAURANT_TABLE(
  TABLE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  SEATING_CAPACITY INT NOT NULL,
  RESTAURANT_ID INT NOT NULL,
  foreign key (RESTAURANT_ID) references RESTAURANT(RESTAURANT_ID)
);

CREATE TABLE TEST.RESERVATION(
  RESERVATION_ID INT AUTO_INCREMENT  PRIMARY KEY,
  TABLE_ID INT NOT NULL,
  START TIMESTAMP NOT NULL,
  END TIMESTAMP NOT NULL,
  foreign key (TABLE_ID) references RESTAURANT_TABLE(TABLE_ID)
);